**** Pidgins -- formal expansion of 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ UP: <piddev00>
A pidgin undergoes formal expansion on either or both of the following two conditions: First, if it has stabilized; second, if it has acquired native speakers.  In the latter circumstance, although immigrants might still be learning a stabilized, expanding pidgin, the native speakers would be speaking a creole, rather than a pidgin language.  If the creole developed abruptly from a jargon or unstable pidgin (usually for demographic reasons of massive population change and natural increase) then formal expansion would also mark the transition from pidgin to creole.  In either case, the pidgin acquired by later immigrants as a second or later language would be expanded, eventually to the point where the process would be second (or later) language acquisition proper rather than the acquisition of a stable pidgin.

 -- Stabilization of pidgins ...................... <piddev.stb>
 -- Functional expansion of pidgins ............... <pid-func.2>
 -- What is the language spoken between a creole 
    speaker and a pidgin speaker? ............... <schu-pid.com>

